import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // wrangler-generated, regenerated by `npm run cf-typegen` — don't lint it.
    "cloudflare-env.d.ts",
    // OpenNext/Wrangler build output and local state — not source.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
